env:
  es6: true

plugins:
  - fp

extends:
  - "plugin:fp/recommended"

rules:
  max-lines:
    - warn
    - 200
  max-lines-per-function:
    - warn
    - 20
  complexity:
    - warn
    - 5
  max-nested-callbacks:
    - warn
    - 2
  max-depth:
    - warn
    - 3
  max-params:
    - warn
    - 2
